### ISSUE TITLE
Allow configuring annotations for resources

### ISSUE THREAD

**Issue by AndresPineros** [safesoftware/helm-charts#49]
Please allow configuring the annotations from the values.yml. Annotations are very important when integrating services with other Kubernetes system applications. My use case is the kubernetes-downscaler, I want to annotate the FME components so that the downscaler knows how many replicas it needs whenever its time to upscale.

```
annotations:
      downscaler/uptime: "Mon-Fri 07:00-21:00 US/Eastern"
      downscaler/original-replicas: "1"
```

**Comment by garnold54** [comment]
Thanks for the report! I agree this is something that we should add to the helm chart, and it should be fairly straight-forward.

**Comment by garnold54** [comment]
Annotations are now supported in the 2019.1.0 chart. They are exposed on the deployments and stateful sets and their associated templates. The syntax in the values.yaml file is:
```
annotations:
  core:
    statefulset: {}
    template: {}
  engine:
    deployment: {}
    template: {}
  queue:
    statefulset: {}
    template: {}
  websocket:
    statefulset: {}
    template: {}
```
