### ISSUE TITLE
Unstable engine names (podname) and Engine assignment rules

### ISSUE THREAD

**Issue by BWibo** [safesoftware/helm-charts#88]
Currently, engine names in FME server equal pod names:

```console
$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
engine-general-95c9d95b5-lptkg        1/1     Running   0          36d
engine-threadripper-c69dc74c7-d6h7r   1/1     Running   0          36d
engine-ssd-5bf779787d-qhvgb           1/1     Running   0          36d
engine-general-95c9d95b5-xclj4        1/1     Running   0          20d
queue-0                               1/1     Running   0          35d
fmeserver-postgresql-0                1/1     Running   0          7d5h
websocket-0                           1/1     Running   0          7d5h
core-0                                2/2     Running   0          7d5h
```

![grafik](https://user-images.githubusercontent.com/7643434/213223747-4107f3dc-9c1b-4453-9c4e-ba6b03050698.png)

## Problem

This is problematic, as podnames may change, for instance, if a node dies and a pod has to be rescheduled or needs to be recreated for some other reason.

For instance, my engine assignment rules fail, because the engine it uses does no longer exists, when the podname changes:

### Situation before

```console
$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
engine-general-95c9d95b5-lptkg        1/1     Running   0          36d
engine-general-95c9d95b5-xclj4        1/1     Running   0          20d
engine-threadripper-c69dc74c7-d6h7r   1/1     Running   0          36d
engine-ssd-5bf779787d-qhvgb           1/1     Running   0          36d
```

![grafik](https://user-images.githubusercontent.com/7643434/213225361-abeac4eb-e766-4dbc-86f8-f3f66c172fd1.png)

### Delete an engine pod

```console
$ kubectl delete pod engine-general-95c9d95b5-lptkg
pod "engine-general-95c9d95b5-lptkg" deleted

$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
engine-general-95c9d95b5-8wgqt        1/1     Running   0          2m43s
engine-general-95c9d95b5-xclj4        1/1     Running   0          20d
engine-ssd-5bf779787d-qhvgb           1/1     Running   0          36d
engine-threadripper-c69dc74c7-d6h7r   1/1     Running   0          36d
```

The newly scheduled engine pod is now named `engine-general-95c9d95b5-8wgqt`. This is not automatically reflected in e.g. 
*Engine Assignement Rules* based on engine names, which leads e.g. jobs no longer being processed, because a *Queue* has no longer engines assigned.

## Questions

* Is there a way to avoid this issue, e.g. using custom engine properties specified in `values.yml`:
  
   ```yaml
   engines:
    debugLevel: "SUPER_VERBOSE"
    hideHostContent: true
    readOnlyQueues: true
    enginesNodeManaged: false
    receiveTimeout: 0
    groups:
      - name: "general"
        engines: 2        
        # Can I somehow use this for engine assignement?
        engineProperties: "generalPurpose"
        type: "STANDARD"
        labels: {}
        affinity: {}
    ```

* Is there a way to give an engine a stable name/identifier?
